package com.example.localization

enum class AppLanguage(val code: String, val label: String) {
    EN("en", "English"),
    FR("fr", "Français")
}

object FixoStrings {
    private val en = mapOf(
        "auth.sign_in" to "Sign In",
        "auth.create_account" to "Create Account",
        "auth.phone_placeholder" to "+237 6 XX XX XX XX",
        "auth.send_otp" to "Send SMS Security Code (OTP)",
        "auth.continue_with_google" to "Continue with Google",
        "auth.pro_gateway_link" to "👉 Are you a skilled professional? Click here to join the Pro Network",
        "auth.sandbox_title" to "Instant Demo Access (Sandbox Mode)",
        "auth.sandbox_sarah" to "👤 Sarah Jenkins (Client - Bonapriso)",
        "auth.sandbox_marc" to "👨🏾🔧 Marc Dubois (Master Plumber - Akwa)",
        "auth.sandbox_admin" to "🛡️ Administrator KYC & Disputes",
        "auth.otp_title" to "SMS Code Verification",
        "auth.otp_subtitle" to "Enter the 4-digit code sent to your phone number",
        "auth.otp_resend" to "Resend code in",
        "auth.otp_verify" to "Verify and Continue",
        "client.search_semantic_placeholder" to "Describe your issue (e.g. burst pipe under sink, tripping breaker...)",
        "client.flash_banner_title" to "⚡ Immediate Callout — Guaranteed arrival in < 30 minutes",
        "client.flash_banner_cta" to "Activate FIXO Flash ⚡",
        "client.stories_title" to "Live from Job Sites (Stories & Reels)",
        "client.recommended_title" to "Recommended Artisans Nearby",
        "client.standard_pkg" to "Fixo Standard : 12,000 FCFA (Arrival in 1-2 hours)",
        "client.flash_pkg" to "Fixo Flash ⚡ : 15,000 FCFA (Priority arrival under 30 min)",
        "client.zero_cash_warning" to "The full amount is held in the in-app escrow vault. Do NOT pay any physical cash to the artisan on site.",
        "client.scan_camera_cta" to "Scan Artisan's Invoice QR Code",
        "client.enter_pin_backup" to "Or Enter 4-Digit Backup PIN Code",
        "client.summary_conform" to "Work inspected & approved • Turnkey price :",
        "client.authorize_release" to "Authorize Escrow Release (Fingerprint / Face ID)",
        "artisan.online_status" to "ONLINE",
        "artisan.offline_status" to "OFFLINE",
        "artisan.available_balance" to "Available balance",
        "artisan.escrow_holding" to "Funds held in escrow",
        "artisan.cashout_cta" to "⚡ Instant Cash-Out to Mobile Money",
        "artisan.slide_to_accept" to ">>>> Slide to accept mission >>>>",
        "artisan.arrived_site_cta" to "I Have Arrived on Site",
        "artisan.work_finished_cta" to "Work Finished : Generate QR Invoice",
        "artisan.reels_prompt" to "Artisans posting 2 video reels per week receive 4x more customer calls.",
        "reels.book_exact_service" to "Order this exact service • %s",
        "reels.verified_badge" to "Fixo Certified ✓",
        "reels.comments_sheet_title" to "Reviews & Technical Proofs",
        "reels.share_text_template" to "Check out this repair on FIXO by %s for %s : %s",
        "app_tagline" to "On-Demand Certified Artisans & Master Craftsmen",
        "slogan" to "Craftsmanship on Demand",
        "role_customer" to "Customer",
        "role_worker" to "Artisan Pro",
        "role_enterprise" to "Enterprise",
        "role_admin" to "Admin HQ",
        "search_hint" to "Describe issue (e.g. burst pipe, tripping breaker...)",
        "emergency_callout" to "Emergency 30-Min Callout",
        "verified_pro" to "Verified Pro",
        "master_craftsman" to "Master Artisan",
        "top_categories" to "Skilled Trades",
        "featured_artisans" to "Top-Rated Artisans Nearby",
        "watch_reels" to "Craftsmanship Reels",
        "view_all" to "View All",
        "book_now" to "Book Service",
        "chat" to "Chat",
        "track_job" to "Track Job",
        "active_job" to "Active Job in Progress",
        "release_escrow" to "Release Escrow Payment",
        "rate_artisan" to "Review & Release Payment",
        "points_balance" to "FIXO Points",
        "rewards" to "Rewards",
        "wallet" to "Wallet",
        "availability" to "Availability",
        "reels" to "Reels",
        "jobs" to "Jobs",
        "profile" to "Profile",
        "categories" to "Categories",
        "home" to "Home",
        "nav_explore" to "Explore",
        "nav_reels" to "Reels",
        "nav_jobs" to "Jobs",
        "nav_account" to "Account",
        "pro_nav_cockpit" to "Cockpit",
        "pro_nav_schedule" to "Planning",
        "pro_nav_reels" to "Studio Reels",
        "pro_nav_jobs" to "Missions",
        "pro_nav_profile" to "Profil Pro",
        "radar_badge" to "certified technicians available in",
        "flash_banner_title" to "⚡ Emergency Callout — Guaranteed arrival < 30 minutes",
        "flash_banner_cta" to "Activate FIXO Flash",
        "emergency_leak" to "🚰 Water Leak",
        "emergency_power" to "⚡ Short Circuit",
        "emergency_ac" to "❄️ AC Failure",
        "emergency_lock" to "🚪 Locked Door",
        "emergency_masonry" to "🧱 Masonry",
        "turnkey_notice" to "The full amount is held in the in-app escrow vault. Do NOT pay any physical cash to the artisan on site.",
        "standard_rate" to "Fixo Standard : 12 000 FCFA (Arrival in 1-2 hours)",
        "flash_rate" to "Fixo Flash ⚡ : 15 000 FCFA (Priority arrival under 30 min)",
        "lock_escrow_cta" to "Lock in Escrow Vault",
        "scan_qr_cta" to "Scan Artisan's Invoice QR",
        "enter_backup_pin" to "Or Enter 4-Digit Backup PIN",
        "conform_summary" to "Work inspected & approved • Turnkey price :",
        "biometric_auth_cta" to "Authorize Escrow Release",
        "trust_seal_cni" to "Biometric ID Verified (National ID / Passport)",
        "trust_seal_record" to "Clean Criminal Record (Bulletin #3)",
        "trust_seal_skills" to "Certified Technical Craftsmanship",
        "trust_seal_shield" to "Fixo Shield Guarantee (Property Damage Included)",
        "online_status" to "ONLINE",
        "offline_status" to "OFFLINE",
        "online_desc" to "Receiving emergency dispatch alerts nearby",
        "offline_desc" to "Unavailable / on break",
        "dispatch_alert_title" to "⚡ INCOMING FLASH MISSION",
        "net_guaranteed" to "Guaranteed Net Payout",
        "slide_to_accept" to ">>>> Slide to accept mission >>>>",
        "refuse_mission" to "Decline",
        "arrived_btn" to "I Have Arrived on Site",
        "require_before_photo" to "Before Photo required before starting work",
        "finish_job_btn" to "Work Finished : Generate QR Invoice",
        "dynamic_qr_title" to "Show this QR Code to Customer",
        "backup_pin_label" to "BACKUP PIN CODE",
        "waiting_scan" to "Waiting for customer scan...",
        "cashout_fee_note" to "Platform fee: 0 FCFA • Processing time: Instant (< 30s)",
        "tier_verified" to "Verified Artisan (15% commission)",
        "tier_pro" to "Pro Artisan (12% commission)",
        "tier_master" to "Master Artisan (8% commission + priority)",
        "reels_incentive" to "Artisans posting 2 video reels weekly receive 4x more direct calls.",
        "film_reel_cta" to "+ Film a Demonstration",
        "enterprise_portal" to "Enterprise Workforce",
        "admin_portal" to "FIXO Operations Portal",
        "escrow_guarantee" to "Escrow Protected • 100% Satisfaction Guarantee",
        "mobile_money" to "MTN & Orange Mobile Money Supported",
        "slots_available" to "Select Available Time Slot",
        "job_scope" to "Describe the Issue & Attach Scope",
        "instant_booking" to "Confirm & Hold in Escrow",
        "share_reel" to "Share Reel",
        "report" to "Report",
        "like" to "Applaud",
        "deposit" to "Deposit Funds",
        "withdraw" to "Withdraw Payout",
        "subscription_starter" to "Starter Tier",
        "subscription_pro" to "Pro Tier",
        "subscription_premium" to "Master Tier",
        "disputes" to "Disputes",
        "verification_pending" to "Verification in Review",
        "verification_approved" to "ID & Trade Certificate Verified",
        "filter_all" to "All",
        "filter_rating" to "4.5+ Rating",
        "filter_verified" to "Verified Only",
        "filter_emergency" to "Emergency Ready",
        "starting_at" to "From",
        "per_hour" to "/ hr",
        "reviews" to "reviews",
        "completed_jobs" to "jobs done",
        // Authentication
        "sign_in" to "Sign In",
        "create_account" to "Create Account",
        "continue_with_google" to "Continue with Google",
        "email_address" to "Email Address",
        "password" to "Password",
        "full_name" to "Full Name",
        "phone_number" to "Phone Number (+237...)",
        "sign_in_submit" to "Sign In to FIXO",
        "sign_up_submit" to "Create FIXO Account",
        "dev_sandbox_title" to "Development Sandbox / Test Profiles",
        "dev_sandbox_desc" to "Switch quickly between verified customer, artisan, and admin roles:",
        "clean_prod_mode" to "Clean Production Mode (Empty States)",
        "load_sample_data" to "Load Sample Sandbox Data",
        "reset_to_empty" to "Clear All Test Data",
        // Reels Studio
        "upload_reel" to "Publish Craftsmanship Reel",
        "reel_title" to "Reel Title",
        "reel_desc" to "Technique Description & Method",
        "reel_category" to "Trade Category",
        "reel_tags" to "Tags & Skills (e.g. CopperBrazing, HVAC)",
        "reel_video_url" to "Video Media (URL or Local File)",
        "reel_thumb_url" to "Thumbnail Cover Image",
        "select_video" to "Select Video",
        "select_cover" to "Select Cover Image",
        "save_draft" to "Save Draft",
        "publish_now" to "Publish Reel",
        "edit_reel" to "Edit Reel",
        "delete_reel" to "Delete Reel",
        "my_reels" to "My Portfolio Reels",
        "reel_published_success" to "Reel successfully published to marketplace!",
        "reel_draft_saved" to "Reel saved as draft.",
        "reel_deleted" to "Reel removed from marketplace.",
        "reel_link_copied" to "Canonical Reel Link copied: https://fixo.cm/reels/",
        "book_from_reel" to "Book This Artisan",
        // Empty states
        "empty_artisans" to "No certified artisans found matching your criteria in Cameroon.",
        "empty_reels" to "No craftsmanship reels published yet. Be the first artisan to show your work!",
        "empty_bookings" to "No active or past bookings. Search certified trades to request an intervention.",
        "empty_transactions" to "No financial activity recorded yet. Deposits and escrow releases will appear here.",
        "empty_projects" to "No enterprise projects currently commissioned.",
        "empty_disputes" to "No disputes filed. Operations running smoothly.",
        // Currency and payment
        "currency_xaf" to "FCFA",
        "payment_method" to "Payment Method",
        "payment_mobile_money" to "MTN Mobile Money / Orange Money",
        "deposit_amount" to "Top-Up Amount (FCFA)",
        "withdraw_amount" to "Withdrawal Amount (FCFA)",
        "available_balance" to "Available Balance",
        "escrow_locked" to "Held in Escrow",
        "confirm_deposit" to "Top Up Wallet",
        "confirm_withdraw" to "Transfer Payout",
        // Job tracking
        "status_requested" to "Service Requested",
        "status_accepted" to "Artisan Accepted",
        "status_en_route" to "Artisan En Route",
        "status_in_progress" to "Work in Progress",
        "status_completed" to "Job Completed",
        "status_disputed" to "Dispute Raised",
        "job_details" to "Intervention Scope & Details",
        "artisan_location" to "Artisan Live GPS Position",
        "send_message" to "Send Message",
        "message_hint" to "Type message to artisan...",
        "open_dispute" to "File Escrow Dispute"
    )

    private val fr = mapOf(
        "auth.sign_in" to "Se Connecter",
        "auth.create_account" to "Créer un Compte",
        "auth.phone_placeholder" to "+237 6 XX XX XX XX",
        "auth.send_otp" to "Envoyer le code de sécurité SMS (OTP)",
        "auth.continue_with_google" to "Continuer avec Google",
        "auth.pro_gateway_link" to "👉 Vous êtes un professionnel ? Cliquez ici pour rejoindre le réseau Pro",
        "auth.sandbox_title" to "Accès Démo Immédiat (Mode Sandbox)",
        "auth.sandbox_sarah" to "👤 Sarah Jenkins (Cliente - Bonapriso)",
        "auth.sandbox_marc" to "👨🏾🔧 Marc Dubois (Maître Plombier - Akwa)",
        "auth.sandbox_admin" to "🛡️ Administrateur KYC & Litiges",
        "auth.otp_title" to "Vérification par Code SMS",
        "auth.otp_subtitle" to "Saisissez le code à 4 chiffres envoyé à votre numéro",
        "auth.otp_resend" to "Renvoyer le code dans",
        "auth.otp_verify" to "Valider et Accéder",
        "client.search_semantic_placeholder" to "Décrivez votre panne (ex. tuyau percé sous l'évier, disjoncteur qui saute...)",
        "client.flash_banner_title" to "⚡ Dépannage Immédiat — Arrivée garantie en < 30 minutes",
        "client.flash_banner_cta" to "Activer FIXO Flash ⚡",
        "client.stories_title" to "En Direct des Chantiers (Stories & Reels)",
        "client.recommended_title" to "Artisans Recommandés à Proximité",
        "client.standard_pkg" to "Fixo Standard : 12 000 FCFA (Arrivée d'ici 1 à 2 heures)",
        "client.flash_pkg" to "Fixo Flash ⚡ : 15 000 FCFA (Arrivée prioritaire sous 30 min)",
        "client.zero_cash_warning" to "Le montant total est sécurisé dans l'application. Vous ne devez verser AUCUN argent liquide à l'artisan sur place.",
        "client.scan_camera_cta" to "Scanner le QR Code de l'Artisan",
        "client.enter_pin_backup" to "Ou Saisir le Code PIN à 4 chiffres",
        "client.summary_conform" to "Travaux conformes • Montant forfaitaire :",
        "client.authorize_release" to "Autoriser la Libération Séquestre (Empreinte / Face ID)",
        "artisan.online_status" to "EN LIGNE",
        "artisan.offline_status" to "HORS LIGNE",
        "artisan.available_balance" to "Solde disponible",
        "artisan.escrow_holding" to "Fonds sous séquestre",
        "artisan.cashout_cta" to "⚡ Retirer mes gains vers Mobile Money",
        "artisan.slide_to_accept" to ">>>> Glisser pour accepter la mission >>>>",
        "artisan.arrived_site_cta" to "Je suis arrivé sur place",
        "artisan.work_finished_cta" to "Travaux terminés : Générer ma facture",
        "artisan.reels_prompt" to "Les artisans qui publient 2 vidéos par semaine reçoivent 4 fois plus d'appels.",
        "reels.book_exact_service" to "Commander cette prestation exacte • %s",
        "reels.verified_badge" to "Certifié Fixo ✓",
        "reels.comments_sheet_title" to "Avis & Preuves Techniques",
        "reels.share_text_template" to "Regarde cette réparation sur FIXO par %s pour %s : %s",
        "app_tagline" to "Artisans Certifiés & Maîtres de Métier sur Demande",
        "slogan" to "L'Excellence à votre Porte",
        "role_customer" to "Client",
        "role_worker" to "Artisan Pro",
        "role_enterprise" to "Entreprise",
        "role_admin" to "Admin HQ",
        "search_hint" to "Décrivez votre panne (ex. tuyau percé, disjoncteur qui saute...)",
        "emergency_callout" to "Dépannage d'Urgence (30 min)",
        "verified_pro" to "Artisan Vérifié",
        "master_craftsman" to "Maître Artisan",
        "top_categories" to "Corps de Métier",
        "featured_artisans" to "Artisans les Mieux Notés à Proximité",
        "watch_reels" to "Vidéos de Réalisations",
        "view_all" to "Tout Afficher",
        "book_now" to "Réserver l'Artisan",
        "chat" to "Messagerie",
        "track_job" to "Suivi d'Intervention",
        "active_job" to "Intervention en Cours",
        "release_escrow" to "Libérer le Paiement Séquestre",
        "rate_artisan" to "Évaluer & Libérer les Fonds",
        "points_balance" to "Points FIXO",
        "rewards" to "Récompenses",
        "wallet" to "Portefeuille",
        "availability" to "Disponibilités",
        "reels" to "Réalisations",
        "jobs" to "Interventions",
        "profile" to "Profil",
        "categories" to "Catégories",
        "home" to "Accueil",
        "nav_explore" to "Explorer",
        "nav_reels" to "Reels",
        "nav_jobs" to "Chantiers",
        "nav_account" to "Compte",
        "pro_nav_cockpit" to "Cockpit",
        "pro_nav_schedule" to "Planning",
        "pro_nav_reels" to "Studio Reels",
        "pro_nav_jobs" to "Missions",
        "pro_nav_profile" to "Profil Pro",
        "radar_badge" to "techniciens certifiés disponibles à",
        "flash_banner_title" to "⚡ Dépannage Immédiat — Arrivée garantie en < 30 minutes",
        "flash_banner_cta" to "Activer FIXO Flash",
        "emergency_leak" to "🚰 Fuite d'eau",
        "emergency_power" to "⚡ Court-circuit",
        "emergency_ac" to "❄️ Panne clim",
        "emergency_lock" to "🚪 Serrure bloquée",
        "emergency_masonry" to "🧱 Maçonnerie",
        "turnkey_notice" to "Le montant total est sécurisé dans l'application. Vous ne devez verser AUCUN argent liquide à l'artisan sur place.",
        "standard_rate" to "Fixo Standard : 12 000 FCFA (Arrivée d'ici 1 à 2 heures)",
        "flash_rate" to "Fixo Flash ⚡ : 15 000 FCFA (Arrivée prioritaire sous 30 min)",
        "lock_escrow_cta" to "Bloquer dans le Coffre Séquestre",
        "scan_qr_cta" to "Scanner le QR Facture de l'Artisan",
        "enter_backup_pin" to "Ou Saisir le Code PIN de Secours (4 chiffres)",
        "conform_summary" to "Travaux conformes • Montant forfaitaire :",
        "biometric_auth_cta" to "Autoriser le Paiement Séquestre",
        "trust_seal_cni" to "Identité Biométrique Validée (CNI / Passeport)",
        "trust_seal_record" to "Casier Judiciaire Vierge (Bulletin n°3)",
        "trust_seal_skills" to "Compétences Techniques Certifiées",
        "trust_seal_shield" to "Couverture Fixo Shield (Garantie Casse Incluse)",
        "online_status" to "EN LIGNE",
        "offline_status" to "HORS LIGNE",
        "online_desc" to "Je reçois des alertes d'intervention autour de moi",
        "offline_desc" to "Je suis indisponible / en pause",
        "dispatch_alert_title" to "⚡ MISSION FLASH ENTRANTE",
        "net_guaranteed" to "Gain Net Garanti",
        "slide_to_accept" to ">>>> Glisser pour accepter la mission >>>>",
        "refuse_mission" to "Refuser",
        "arrived_btn" to "Je suis arrivé sur place",
        "require_before_photo" to "Photo d'état initial requise avant de commencer",
        "finish_job_btn" to "Travaux terminés : Générer ma facture",
        "dynamic_qr_title" to "Présentez ce QR Code au Client",
        "backup_pin_label" to "CODE PIN DE SECOURS",
        "waiting_scan" to "En attente du scan du client...",
        "cashout_fee_note" to "Frais de retrait plateforme : 0 FCFA • Délai : Instantané (< 30s)",
        "tier_verified" to "Artisan Vérifié (15% commission)",
        "tier_pro" to "Artisan Pro (12% commission)",
        "tier_master" to "Maître Artisan (8% commission + priorité)",
        "reels_incentive" to "Les artisans qui publient 2 vidéos par semaine reçoivent 4 fois plus d'appels.",
        "film_reel_cta" to "+ Filmer une réalisation",
        "enterprise_portal" to "Main d'Œuvre Entreprise",
        "admin_portal" to "Portail Opérations FIXO",
        "escrow_guarantee" to "Paiement Séquestré • Garantie Satisfaction 100%",
        "mobile_money" to "Compatible MTN & Orange Mobile Money",
        "slots_available" to "Choisir un Créneau Disponible",
        "job_scope" to "Description du Problème & Détails",
        "instant_booking" to "Confirmer & Bloquer en Séquestre",
        "share_reel" to "Partager la Vidéo",
        "report" to "Signaler",
        "like" to "Applaudir",
        "deposit" to "Recharger le Compte",
        "withdraw" to "Retirer les Gains",
        "subscription_starter" to "Formule Débutant",
        "subscription_pro" to "Formule Pro",
        "subscription_premium" to "Formule Maître",
        "disputes" to "Litiges",
        "verification_pending" to "Vérification en Cours",
        "verification_approved" to "Identité & Diplôme Professionnel Validés",
        "filter_all" to "Tous",
        "filter_rating" to "Note 4.5+",
        "filter_verified" to "Vérifiés Uniquement",
        "filter_emergency" to "Urgence Disponible",
        "starting_at" to "À partir de",
        "per_hour" to "/ h",
        "reviews" to "avis",
        "completed_jobs" to "chantiers terminés",
        // Authentication
        "sign_in" to "Connexion",
        "create_account" to "Créer un Compte",
        "continue_with_google" to "Continuer avec Google",
        "email_address" to "Adresse Email",
        "password" to "Mot de Passe",
        "full_name" to "Nom Complet",
        "phone_number" to "Numéro de Téléphone (+237...)",
        "sign_in_submit" to "Se Connecter à FIXO",
        "sign_up_submit" to "Créer Mon Compte FIXO",
        "dev_sandbox_title" to "Bac à Sable Développeur / Profils de Test",
        "dev_sandbox_desc" to "Basculez rapidement entre client vérifié, artisan et admin :",
        "clean_prod_mode" to "Mode Production Propre (États Vides)",
        "load_sample_data" to "Charger Données du Bac à Sable",
        "reset_to_empty" to "Effacer Données de Test",
        // Reels Studio
        "upload_reel" to "Publier une Vidéo de Réalisation",
        "reel_title" to "Titre de la Vidéo",
        "reel_desc" to "Explication de la Technique & Méthode",
        "reel_category" to "Corps de Métier",
        "reel_tags" to "Mots-Clés & Compétences (ex. BrasageCuivre, CVC)",
        "reel_video_url" to "Fichier Vidéo (URL ou Local)",
        "reel_thumb_url" to "Image de Couverture",
        "select_video" to "Sélectionner Vidéo",
        "select_cover" to "Sélectionner Image",
        "save_draft" to "Enregistrer Brouillon",
        "publish_now" to "Publier la Vidéo",
        "edit_reel" to "Modifier la Vidéo",
        "delete_reel" to "Supprimer la Vidéo",
        "my_reels" to "Mes Vidéos Portfolio",
        "reel_published_success" to "Vidéo publiée avec succès sur FIXO !",
        "reel_draft_saved" to "Vidéo sauvegardée en brouillon.",
        "reel_deleted" to "Vidéo supprimée.",
        "reel_link_copied" to "Lien officiel copié : https://fixo.cm/reels/",
        "book_from_reel" to "Réserver cet Artisan",
        // Empty states
        "empty_artisans" to "Aucun artisan certifié trouvé selon vos filtres au Cameroun.",
        "empty_reels" to "Aucune vidéo de savoir-faire publiée. Soyez le premier artisan à montrer votre travail !",
        "empty_bookings" to "Aucune intervention en cours ou passée. Recherchez un artisan pour démarrer.",
        "empty_transactions" to "Aucune transaction enregistrée. Vos recharges et paiements séquestres apparaîtront ici.",
        "empty_projects" to "Aucun projet d'entreprise en cours de réalisation.",
        "empty_disputes" to "Aucun litige signalé. Toutes les opérations sont conformes.",
        // Currency and payment
        "currency_xaf" to "FCFA",
        "payment_method" to "Moyen de Paiement",
        "payment_mobile_money" to "MTN Mobile Money / Orange Money",
        "deposit_amount" to "Montant de Recharge (FCFA)",
        "withdraw_amount" to "Montant à Retirer (FCFA)",
        "available_balance" to "Solde Disponible",
        "escrow_locked" to "Séquestré en Garantie",
        "confirm_deposit" to "Recharger Mon Compte",
        "confirm_withdraw" to "Demander le Virement",
        // Job tracking
        "status_requested" to "Demande Envoyée",
        "status_accepted" to "Artisan Confirmé",
        "status_en_route" to "Artisan en Route",
        "status_in_progress" to "Intervention en Cours",
        "status_completed" to "Intervention Terminée",
        "status_disputed" to "Litige Ouvert",
        "job_details" to "Périmètre & Détails de l'Intervention",
        "artisan_location" to "Position GPS en Direct de l'Artisan",
        "send_message" to "Envoyer",
        "message_hint" to "Écrire à l'artisan...",
        "open_dispute" to "Ouvrir un Litige Séquestre"
    )

    fun get(key: String, language: AppLanguage): String {
        val dict = if (language == AppLanguage.FR) fr else en
        return dict[key] ?: en[key] ?: key
    }

    fun getString(key: String, language: AppLanguage = AppLanguage.FR): String = get(key, language)

    fun t(key: String, language: AppLanguage): String = get(key, language)
}
