package com.example.localization

enum class AppLanguage(val code: String, val label: String) {
    EN("en", "English"),
    FR("fr", "Français")
}

object FixoStrings {
    private val en = mapOf(
        "app_tagline" to "On-Demand Certified Artisans & Master Craftsmen",
        "role_customer" to "Customer",
        "role_worker" to "Artisan Pro",
        "role_enterprise" to "Enterprise",
        "role_admin" to "Admin HQ",
        "search_hint" to "Search plumbers, electricians, carpenters...",
        "emergency_callout" to "Emergency 30-Min Callout",
        "verified_pro" to "Verified Pro",
        "master_craftsman" to "Master Artisan",
        "top_categories" to "Skilled Trades",
        "featured_artisans" to "Top-Rated Artisans Nearby",
        "watch_reels" to "Craftsmanship Reels",
        "view_all" to "View All",
        "book_now" to "Book Service",
        "chat" to "Chat",
        "track_job" to "Track Job",
        "active_job" to "Active Job in Progress",
        "release_escrow" to "Release Escrow Payment",
        "rate_artisan" to "Review & Release Payment",
        "points_balance" to "FIXO Points",
        "rewards" to "Rewards",
        "wallet" to "Wallet",
        "availability" to "Availability",
        "reels" to "Reels",
        "jobs" to "Jobs",
        "profile" to "Profile",
        "categories" to "Categories",
        "home" to "Home",
        "enterprise_portal" to "Enterprise Workforce",
        "admin_portal" to "FIXO Operations Portal",
        "escrow_guarantee" to "Escrow Protected • 100% Satisfaction Guarantee",
        "mobile_money" to "MTN & Orange Mobile Money Supported",
        "slots_available" to "Select Available Time Slot",
        "job_scope" to "Describe the Issue & Attach Scope",
        "instant_booking" to "Confirm & Hold in Escrow",
        "share_reel" to "Share Reel",
        "report" to "Report",
        "like" to "Applaud",
        "deposit" to "Deposit Funds",
        "withdraw" to "Withdraw Payout",
        "subscription_starter" to "Starter Tier",
        "subscription_pro" to "Pro Tier",
        "subscription_premium" to "Master Tier",
        "disputes" to "Disputes",
        "verification_pending" to "Verification in Review",
        "verification_approved" to "ID & Trade Certificate Verified",
        "filter_all" to "All",
        "filter_rating" to "4.5+ Rating",
        "filter_verified" to "Verified Only",
        "filter_emergency" to "Emergency Ready",
        "starting_at" to "From",
        "per_hour" to "/ hr",
        "reviews" to "reviews",
        "completed_jobs" to "jobs done",
        // Authentication
        "sign_in" to "Sign In",
        "create_account" to "Create Account",
        "continue_with_google" to "Continue with Google",
        "email_address" to "Email Address",
        "password" to "Password",
        "full_name" to "Full Name",
        "phone_number" to "Phone Number (+237...)",
        "sign_in_submit" to "Sign In to FIXO",
        "sign_up_submit" to "Create FIXO Account",
        "dev_sandbox_title" to "Development Sandbox / Test Profiles",
        "dev_sandbox_desc" to "Switch quickly between verified customer, artisan, and admin roles:",
        "clean_prod_mode" to "Clean Production Mode (Empty States)",
        "load_sample_data" to "Load Sample Sandbox Data",
        "reset_to_empty" to "Clear All Test Data",
        // Reels Studio
        "upload_reel" to "Publish Craftsmanship Reel",
        "reel_title" to "Reel Title",
        "reel_desc" to "Technique Description & Method",
        "reel_category" to "Trade Category",
        "reel_tags" to "Tags & Skills (e.g. CopperBrazing, HVAC)",
        "reel_video_url" to "Video Media (URL or Local File)",
        "reel_thumb_url" to "Thumbnail Cover Image",
        "select_video" to "Select Video",
        "select_cover" to "Select Cover Image",
        "save_draft" to "Save Draft",
        "publish_now" to "Publish Reel",
        "edit_reel" to "Edit Reel",
        "delete_reel" to "Delete Reel",
        "my_reels" to "My Portfolio Reels",
        "reel_published_success" to "Reel successfully published to marketplace!",
        "reel_draft_saved" to "Reel saved as draft.",
        "reel_deleted" to "Reel removed from marketplace.",
        "reel_link_copied" to "Canonical Reel Link copied: https://fixo.cm/reels/",
        "book_from_reel" to "Book This Artisan",
        // Empty states
        "empty_artisans" to "No certified artisans found matching your criteria in Cameroon.",
        "empty_reels" to "No craftsmanship reels published yet. Be the first artisan to show your work!",
        "empty_bookings" to "No active or past bookings. Search certified trades to request an intervention.",
        "empty_transactions" to "No financial activity recorded yet. Deposits and escrow releases will appear here.",
        "empty_projects" to "No enterprise projects currently commissioned.",
        "empty_disputes" to "No disputes filed. Operations running smoothly.",
        // Currency and payment
        "currency_xaf" to "FCFA",
        "payment_method" to "Payment Method",
        "payment_mobile_money" to "MTN Mobile Money / Orange Money",
        "deposit_amount" to "Top-Up Amount (FCFA)",
        "withdraw_amount" to "Withdrawal Amount (FCFA)",
        "available_balance" to "Available Balance",
        "escrow_locked" to "Held in Escrow",
        "confirm_deposit" to "Top Up Wallet",
        "confirm_withdraw" to "Transfer Payout",
        // Job tracking
        "status_requested" to "Service Requested",
        "status_accepted" to "Artisan Accepted",
        "status_en_route" to "Artisan En Route",
        "status_in_progress" to "Work in Progress",
        "status_completed" to "Job Completed",
        "status_disputed" to "Dispute Raised",
        "job_details" to "Intervention Scope & Details",
        "artisan_location" to "Artisan Live GPS Position",
        "send_message" to "Send Message",
        "message_hint" to "Type message to artisan...",
        "open_dispute" to "File Escrow Dispute"
    )

    private val fr = mapOf(
        "app_tagline" to "Artisans Certifiés & Maîtres de Métier sur Demande",
        "role_customer" to "Client",
        "role_worker" to "Artisan Pro",
        "role_enterprise" to "Entreprise",
        "role_admin" to "Admin HQ",
        "search_hint" to "Rechercher plombiers, électriciens, menuisiers...",
        "emergency_callout" to "Dépannage d'Urgence (30 min)",
        "verified_pro" to "Artisan Vérifié",
        "master_craftsman" to "Maître Artisan",
        "top_categories" to "Corps de Métier",
        "featured_artisans" to "Artisans les Mieux Notés à Proximité",
        "watch_reels" to "Vidéos de Réalisations",
        "view_all" to "Tout Afficher",
        "book_now" to "Réserver l'Artisan",
        "chat" to "Messagerie",
        "track_job" to "Suivi d'Intervention",
        "active_job" to "Intervention en Cours",
        "release_escrow" to "Libérer le Paiement Séquestre",
        "rate_artisan" to "Évaluer & Libérer les Fonds",
        "points_balance" to "Points FIXO",
        "rewards" to "Récompenses",
        "wallet" to "Portefeuille",
        "availability" to "Disponibilités",
        "reels" to "Réalisations",
        "jobs" to "Interventions",
        "profile" to "Profil",
        "categories" to "Catégories",
        "home" to "Accueil",
        "enterprise_portal" to "Main d'Œuvre Entreprise",
        "admin_portal" to "Portail Opérations FIXO",
        "escrow_guarantee" to "Paiement Séquestré • Garantie Satisfaction 100%",
        "mobile_money" to "Compatible MTN & Orange Mobile Money",
        "slots_available" to "Choisir un Créneau Disponible",
        "job_scope" to "Description du Problème & Détails",
        "instant_booking" to "Confirmer & Bloquer en Séquestre",
        "share_reel" to "Partager la Vidéo",
        "report" to "Signaler",
        "like" to "Applaudir",
        "deposit" to "Recharger le Compte",
        "withdraw" to "Retirer les Gains",
        "subscription_starter" to "Formule Débutant",
        "subscription_pro" to "Formule Pro",
        "subscription_premium" to "Formule Maître",
        "disputes" to "Litiges",
        "verification_pending" to "Vérification en Cours",
        "verification_approved" to "Identité & Diplôme Professionnel Validés",
        "filter_all" to "Tous",
        "filter_rating" to "Note 4.5+",
        "filter_verified" to "Vérifiés Uniquement",
        "filter_emergency" to "Urgence Disponible",
        "starting_at" to "À partir de",
        "per_hour" to "/ h",
        "reviews" to "avis",
        "completed_jobs" to "chantiers terminés",
        // Authentication
        "sign_in" to "Connexion",
        "create_account" to "Créer un Compte",
        "continue_with_google" to "Continuer avec Google",
        "email_address" to "Adresse Email",
        "password" to "Mot de Passe",
        "full_name" to "Nom Complet",
        "phone_number" to "Numéro de Téléphone (+237...)",
        "sign_in_submit" to "Se Connecter à FIXO",
        "sign_up_submit" to "Créer Mon Compte FIXO",
        "dev_sandbox_title" to "Bac à Sable Développeur / Profils de Test",
        "dev_sandbox_desc" to "Basculez rapidement entre client vérifié, artisan et admin :",
        "clean_prod_mode" to "Mode Production Propre (États Vides)",
        "load_sample_data" to "Charger Données du Bac à Sable",
        "reset_to_empty" to "Effacer Données de Test",
        // Reels Studio
        "upload_reel" to "Publier une Vidéo de Réalisation",
        "reel_title" to "Titre de la Vidéo",
        "reel_desc" to "Explication de la Technique & Méthode",
        "reel_category" to "Corps de Métier",
        "reel_tags" to "Mots-Clés & Compétences (ex. BrasageCuivre, CVC)",
        "reel_video_url" to "Fichier Vidéo (URL ou Local)",
        "reel_thumb_url" to "Image de Couverture",
        "select_video" to "Sélectionner Vidéo",
        "select_cover" to "Sélectionner Image",
        "save_draft" to "Enregistrer Brouillon",
        "publish_now" to "Publier la Vidéo",
        "edit_reel" to "Modifier la Vidéo",
        "delete_reel" to "Supprimer la Vidéo",
        "my_reels" to "Mes Vidéos Portfolio",
        "reel_published_success" to "Vidéo publiée avec succès sur FIXO !",
        "reel_draft_saved" to "Vidéo sauvegardée en brouillon.",
        "reel_deleted" to "Vidéo supprimée.",
        "reel_link_copied" to "Lien officiel copié : https://fixo.cm/reels/",
        "book_from_reel" to "Réserver cet Artisan",
        // Empty states
        "empty_artisans" to "Aucun artisan certifié trouvé selon vos filtres au Cameroun.",
        "empty_reels" to "Aucune vidéo de savoir-faire publiée. Soyez le premier artisan à montrer votre travail !",
        "empty_bookings" to "Aucune intervention en cours ou passée. Recherchez un artisan pour démarrer.",
        "empty_transactions" to "Aucune transaction enregistrée. Vos recharges et paiements séquestres apparaîtront ici.",
        "empty_projects" to "Aucun projet d'entreprise en cours de réalisation.",
        "empty_disputes" to "Aucun litige signalé. Toutes les opérations sont conformes.",
        // Currency and payment
        "currency_xaf" to "FCFA",
        "payment_method" to "Moyen de Paiement",
        "payment_mobile_money" to "MTN Mobile Money / Orange Money",
        "deposit_amount" to "Montant de Recharge (FCFA)",
        "withdraw_amount" to "Montant à Retirer (FCFA)",
        "available_balance" to "Solde Disponible",
        "escrow_locked" to "Séquestré en Garantie",
        "confirm_deposit" to "Recharger Mon Compte",
        "confirm_withdraw" to "Demander le Virement",
        // Job tracking
        "status_requested" to "Demande Envoyée",
        "status_accepted" to "Artisan Confirmé",
        "status_en_route" to "Artisan en Route",
        "status_in_progress" to "Intervention en Cours",
        "status_completed" to "Intervention Terminée",
        "status_disputed" to "Litige Ouvert",
        "job_details" to "Périmètre & Détails de l'Intervention",
        "artisan_location" to "Position GPS en Direct de l'Artisan",
        "send_message" to "Envoyer",
        "message_hint" to "Écrire à l'artisan...",
        "open_dispute" to "Ouvrir un Litige Séquestre"
    )

    fun get(key: String, language: AppLanguage): String {
        val dict = if (language == AppLanguage.FR) fr else en
        return dict[key] ?: en[key] ?: key
    }
}
